# Generated by Django 4.1.2 on 2024-01-03 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('category_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='mouseAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='category_MouseAction_Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='webapp.category')),
                ('mouse_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='webapp.mouseaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
