# Generated by Django 4.1.2 on 2024-01-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_mouseaction_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouseaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mouseaction',
            name='gesture_category',
            field=models.ManyToManyField(blank=True, related_name='mouse_actions', to='webapp.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.IntegerField(choices=[(1, 'Only Index finger Up'), (2, 'Index and middle finger up'), (3, 'Index and thumb finger'), (4, 'Ring finger up'), (5, 'Index and last finger up'), (6, 'All fingers up'), (7, 'All fingers closed')]),
        ),
    ]
