# Generated by Django 5.0.1 on 2024-03-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "webapp",
            "0003_mouseaction_description_mouseaction_gesture_category_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mouseaction",
            name="gif_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mouseaction",
            name="category_id",
            field=models.IntegerField(
                choices=[
                    (1, "Cursor Movement"),
                    (2, "Mouse Left Click"),
                    (3, "Mouse Right Click"),
                    (4, "ScreenShot"),
                    (5, "Zoom In and Zoom Out"),
                    (6, "Clear"),
                ]
            ),
        ),
    ]
