# Generated by Django 5.0.1 on 2024-03-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0004_category_image_url_mouseaction_gif_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
